import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
export const settleMs=3000;
const composers=['[contenteditable="true"][role="textbox"]','.ql-editor[contenteditable="true"]','[contenteditable="true"]','textarea'];
const downloadSelector='button[aria-label*="download" i], [role="button"][aria-label*="download" i], a[aria-label*="download" i], button[title*="download" i], a[title*="download" i], a[download]';
function imageType(b){if(b.length>=8&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return{mime:'image/png',ext:'png'};if(b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255)return{mime:'image/jpeg',ext:'jpg'};if(b.length>=12&&b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP')return{mime:'image/webp',ext:'webp'};throw new Error('E_IMAGE_MAGIC');}
function dims(bytes,mime){if(mime==='image/png'&&bytes.length>=24)return[bytes.readUInt32BE(16),bytes.readUInt32BE(20)];if(mime==='image/jpeg'){let i=2;while(i+9<bytes.length){if(bytes[i]!==255){i++;continue;}const m=bytes[i+1];if(m===216||m===217){i+=2;continue;}if(i+4>bytes.length)break;const len=bytes.readUInt16BE(i+2);if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(m)&&i+9<bytes.length)return[bytes.readUInt16BE(i+7),bytes.readUInt16BE(i+5)];if(len<2)break;i+=2+len;}}return[0,0];}
async function visible(loc){return await loc.isVisible({timeout:300}).catch(()=>false);}async function hrefFor(control){return await control.getAttribute('href').catch(()=>null)||await control.evaluate(el=>el.closest('a')?.href||el.querySelector?.('a')?.href||null).catch(()=>null);}
async function streamBytes(download){let err=null;try{const stream=await download.createReadStream();if(stream){const chunks=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk));const raw=Buffer.concat(chunks);if(raw.length)return raw;}}catch(e){err=e;}try{const p=await download.path();if(p&&fs.existsSync(p)){const raw=fs.readFileSync(p);if(raw.length)return raw;}}catch(e){err=err||e;}try{const tmp=path.join(os.tmpdir(),`fa124-gemini-${crypto.randomUUID()}`);await download.saveAs(tmp);const raw=fs.readFileSync(tmp);fs.rmSync(tmp,{force:true});if(raw.length)return raw;}catch(e){err=err||e;}throw err||new Error('E_DOWNLOAD_NO_BYTES');}
async function sourceBytes(page,context,item){const src=item.src;if(src.startsWith('data:image/')){const raw=Buffer.from(src.slice(src.indexOf(',')+1),'base64');return{bytes:raw,...imageType(raw),width:item.w,height:item.h,method:'provider_data_uri_dom:fresh-generated-dom-after-download-control'};}if(src.startsWith('blob:')){const b64=await page.evaluate(async u=>{const r=await fetch(u);const a=new Uint8Array(await r.arrayBuffer());let s='';for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(s);},src);const raw=Buffer.from(b64,'base64');return{bytes:raw,...imageType(raw),width:item.w,height:item.h,method:'provider_blob_dom:fresh-generated-dom-after-download-control'};}if(/^https?:/.test(src)){const r=await context.request.get(src,{timeout:45000});if(!r.ok())throw new Error(`E_IMAGE_FETCH_HTTP_${r.status()}`);const raw=Buffer.from(await r.body());let host='';try{host=new URL(src).hostname.toLowerCase()}catch{}return{bytes:raw,...imageType(raw),width:item.w,height:item.h,host,method:'provider_image_url_browser_context:fresh-generated-dom-after-download-control'};}throw new Error('E_IMAGE_SOURCE');}
export async function prepare({page}){const state={downloadCount:await page.locator(downloadSelector).count(),baselineImages:new Set(await page.locator('img').evaluateAll(xs=>xs.map(x=>x.currentSrc||x.src||'').filter(Boolean))),committed:false,responses:[],handler:null};state.handler=async response=>{if(!state.committed)return;try{const ct=(response.headers()['content-type']||'').split(';')[0].toLowerCase();if(!ct.startsWith('image/'))return;const raw=Buffer.from(await response.body());if(raw.length<100000)return;const fmt=imageType(raw),d=dims(raw,fmt.mime);if((d[0]&&d[0]<512)||(d[1]&&d[1]<512))return;let host='';try{host=new URL(response.url()).hostname.toLowerCase()}catch{}state.responses.push({bytes:raw,...fmt,width:d[0]||0,height:d[1]||0,host,method:'provider_generated_image_response_body_after_dispatch'});if(state.responses.length>8)state.responses.shift();}catch{}};page.on('response',state.handler);return state;}
export async function submit({page,prompt,state}){for(const selector of composers){const c=page.locator(selector).first();if(!await visible(c))continue;try{await c.click({timeout:1500});await c.fill(prompt,{timeout:4000});state.committed=true;await c.press('Enter');return{composer_selector:selector,send_selector:'composer-enter'};}catch{}}throw new Error('E_GEMINI_COMPOSER_UNAVAILABLE');}
export async function waitForOutput({page,context,state,timeoutMs}){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const loc=page.locator(downloadSelector),count=await loc.count();if(count>state.downloadCount){if(state.responses.length){state.responses.sort((a,b)=>b.bytes.length-a.bytes.length);return state.responses[0];}const fresh=await page.locator('img').evaluateAll(xs=>xs.map(x=>({src:x.currentSrc||x.src||'',w:x.naturalWidth||0,h:x.naturalHeight||0})).filter(x=>x.src&&x.w>=512&&x.h>=512));for(let i=fresh.length-1;i>=0;i--){const item=fresh[i];if(state.baselineImages.has(item.src))continue;try{const got=await sourceBytes(page,context,item);if(got.bytes.length>=50000)return got;}catch{}}for(let i=count-1;i>=state.downloadCount;i--){const control=loc.nth(i);if(!await visible(control))continue;const href=await hrefFor(control);try{const [download]=await Promise.all([page.waitForEvent('download',{timeout:12000}),control.click()]);const raw=await streamBytes(download);if(raw.length>=10000)return{bytes:raw,...imageType(raw),width:0,height:0,method:'provider_browser_download_stream_path_saveas'};}catch{}if(href){const r=await context.request.get(href,{timeout:45000}).catch(()=>null);if(r?.ok()){const raw=Buffer.from(await r.body());if(raw.length>=10000){let host='';try{host=new URL(href).hostname.toLowerCase()}catch{}return{bytes:raw,...imageType(raw),width:0,height:0,host,method:'provider_download_href_browser_context'};}}}}}
const body=(await page.locator('body').innerText({timeout:3000}).catch(()=>'' )).toLowerCase();if(/verify you are human|security check|unusual traffic/.test(body))throw new Error('E_PROTECTION_CHALLENGE');if(/image creation isn.t available|can.t seem to create any|failed to generate/.test(body))throw new Error('E_PROVIDER_GENERATION_FAILED');await page.waitForTimeout(500);}throw new Error('E_BOUNDED_COMPLETION_TIMEOUT');}
export async function cleanup({page,state}){if(state?.handler)page.off('response',state.handler);}
