#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
const arg=(n,d='')=>{const i=process.argv.indexOf(n);return i>=0?String(process.argv[i+1]||''):d};
const num=(n,d)=>{const v=Number(arg(n,String(d)));return Number.isFinite(v)?v:d}; const sleep=ms=>new Promise(r=>setTimeout(r,ms)); const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const SVG_DOC_PATTERN='<svg\\b[\\s\\S]*?</svg>';
class Cdp{constructor(url){this.url=url;this.ws=null;this.seq=0;this.pending=new Map()}async connect(){this.ws=new WebSocket(this.url);await new Promise((r,j)=>{const t=setTimeout(()=>j(new Error('E_CDP_WS_TIMEOUT')),1e4);this.ws.onopen=()=>{clearTimeout(t);r()};this.ws.onerror=()=>{clearTimeout(t);j(new Error('E_CDP_WS'))}});this.ws.onmessage=e=>{let m;try{m=JSON.parse(String(e.data))}catch{return}const p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message||'E_CDP_RPC')):p.resolve(m.result||{})}}send(method,params={}){const id=++this.seq;return new Promise((resolve,reject)=>{const t=setTimeout(()=>{this.pending.delete(id);reject(new Error(`E_CDP_RPC_TIMEOUT:${method}`))},15e3);this.pending.set(id,{resolve:v=>{clearTimeout(t);resolve(v)},reject:e=>{clearTimeout(t);reject(e)}});this.ws.send(JSON.stringify({id,method,params}))})}close(){try{this.ws?.close()}catch{}}}
async function evaluate(cdp,expression){const r=await cdp.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw new Error(`E_RUNTIME_EVALUATE:${r.exceptionDetails.exception?.description||r.exceptionDetails.text||''}`);return r.result?.value}
async function target(port,origin){const end=Date.now()+3e4;while(Date.now()<end){try{const rows=await (await fetch(`http://127.0.0.1:${port}/json/list`,{signal:AbortSignal.timeout(1500)})).json();const t=rows.find(x=>x.type==='page'&&String(x.url||'').startsWith(origin));if(t?.webSocketDebuggerUrl)return t}catch{}await sleep(250)}throw new Error('E_PROVIDER_TARGET')}
async function responseSnapshot(cdp,cfg){return await evaluate(cdp,`(()=>{const sels=${JSON.stringify(cfg.responseRoots||[])};const roots=sels.length?sels.flatMap(s=>[...document.querySelectorAll(s)]):[...document.querySelectorAll('pre,code,article,[data-message-author-role="assistant"],[class*="message" i],[class*="markdown" i],[class*="response" i],[class*="prose" i]')];const out=[],seen=new Set();for(const e of roots){const t=String(e.innerText||e.textContent||'').trim();if(!t)continue;const re=new RegExp(${JSON.stringify(SVG_DOC_PATTERN)},'gi');for(const m of t.matchAll(re)){const x=m[0].trim();if(!x||seen.has(x))continue;const oe=x.indexOf('>');if(oe<4)continue;const r=x.slice(0,oe+1).toLowerCase();if(!(r.includes('viewbox=')||r.includes('xmlns=')||r.includes('width=')))continue;seen.add(x);out.push(x)}}const vis=e=>e&&e.getClientRects().length>0;const buttons=[...document.querySelectorAll('button,[role="button"]')].filter(vis),stop=buttons.some(e=>/stop/i.test(String(e.getAttribute('aria-label')||e.getAttribute('title')||e.innerText||e.textContent||''))&&!e.disabled);return {url:location.href,stop,svgs:out}})()`)}
async function settleThreadBaseline(cdp,cfg,threadUrl){if(!threadUrl)return new Set();const end=Date.now()+30000;let last='',stable=0,snap=null;while(Date.now()<end){snap=await responseSnapshot(cdp,cfg);if(!String(snap.url||'').startsWith(threadUrl))throw new Error(`E_DAILY_THREAD_DRIFT_PRE_SUBMIT:${snap.url||''}`);const sig=JSON.stringify((snap.svgs||[]).map(sha).sort());if(!snap.stop&&sig===last)stable++;else{last=sig;stable=0}if(stable>=3)return new Set((snap.svgs||[]).map(sha));await sleep(750)}throw new Error('E_DAILY_THREAD_BASELINE_UNSTABLE')}
const P={
 claude:{origin:'https://claude.ai',composer:['div[contenteditable="true"][role="textbox"]','[contenteditable="true"]','textarea'],responseRoots:['.font-claude-response']},
 chatgpt:{origin:'https://chatgpt.com',composer:['#prompt-textarea','textarea','[contenteditable="true"]'],responseRoots:['[data-message-author-role="assistant"]']},
 qwen:{origin:'https://chat.qwen.ai',composer:['textarea[placeholder*="Ask Qwen" i]','textarea','[contenteditable="true"][role="textbox"]','[contenteditable="true"]']},
 gemini:{origin:'https://gemini.google.com',composer:['[contenteditable="true"][role="textbox"]','.ql-editor[contenteditable="true"]','[contenteditable="true"]','textarea']},
 grok:{origin:'https://grok.com',composer:['[contenteditable="true"][role="textbox"]','[contenteditable="true"]','textarea']},
 manus:{origin:'https://manus.im',composer:['.tiptap.ProseMirror[contenteditable="true"]','textarea','[contenteditable="true"]']},
 copilot:{origin:'https://copilot.microsoft.com',composer:['textarea','[contenteditable="true"][role="textbox"]','[contenteditable="true"]']},
 duckai:{origin:'https://duck.ai',composer:['textarea[placeholder="Ask anything privately"]','textarea']}
};
const provider=arg('--provider'),cfg=P[provider],port=num('--cdp-port',0),promptFile=arg('--prompt-file'),responseFile=arg('--response-file'),observationFile=arg('--observation-file'),dispatchReceiptFile=arg('--dispatch-receipt',''),threadUrl=arg('--thread-url',''),timeoutMs=num('--timeout-ms',360000);if(!cfg||!port||!promptFile||!responseFile)throw new Error('E_CONFIG');const prompt=fs.readFileSync(promptFile,'utf8');
const t=await target(port,cfg.origin),cdp=new Cdp(t.webSocketDebuggerUrl);await cdp.connect();
try{await cdp.send('Runtime.enable');
 let probe=null;const composerDeadline=Date.now()+45000;while(Date.now()<composerDeadline){probe=await evaluate(cdp,`(()=>{const sels=${JSON.stringify(cfg.composer)},el=sels.flatMap(s=>[...document.querySelectorAll(s)]).find(e=>e.getAttribute('aria-hidden')!=='true'&&e.getClientRects().length>0);const vis=e=>!!e&&(e.getClientRects().length>0);const login=[...document.querySelectorAll('button,a')].some(e=>vis(e)&&/^(log in|sign in)$/i.test((e.innerText||e.textContent||'').trim()));const body=(document.body?.innerText||'').toLowerCase(),challenge=/verify you are human|security check|captcha|unusual traffic/.test(body);return {composer:!!el,auth_required:!el&&(login||challenge),url:location.href,title:document.title}})()`);if(probe.auth_required)throw new Error('E_AUTH_REQUIRED');if(probe.composer)break;await sleep(500)}if(!probe?.composer)throw new Error('E_COMPOSER_NOT_READY');
 const baselineSvgHashes=await settleThreadBaseline(cdp,cfg,threadUrl);
 const fill=await evaluate(cdp,`(()=>{const text=${JSON.stringify(prompt)},sels=${JSON.stringify(cfg.composer)},el=sels.flatMap(s=>[...document.querySelectorAll(s)]).find(e=>e.getAttribute('aria-hidden')!=='true'&&e.getClientRects().length>0);if(!el)return {ok:false};el.focus();if(el instanceof HTMLTextAreaElement||el instanceof HTMLInputElement){const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;if(setter)setter.call(el,text);else el.value=text;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}else{el.textContent='';document.execCommand('insertText',false,text);if((el.innerText||el.textContent||'').length<20)el.textContent=text;el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}))}return {ok:true,chars:String(typeof el.value==='string'?el.value:(el.innerText||el.textContent||'')).length}})()`);if(!fill.ok||fill.chars<Math.min(20,prompt.length))throw new Error('E_PROMPT_INJECT');const beforeUrl=probe.url,beforeResponses=await evaluate(cdp,`(()=>{const sels=${JSON.stringify(cfg.responseRoots||[])};const roots=sels.length?sels.flatMap(s=>[...document.querySelectorAll(s)]):[...document.querySelectorAll('pre,code,article,[data-message-author-role="assistant"],[class*="message" i],[class*="markdown" i],[class*="response" i],[class*="prose" i]')];return roots.length})()`);await sleep(600);
 let submitMethod='ENTER_AFTER_SETTLE';
 if(provider==='chatgpt'||provider==='copilot'){
  const click=await evaluate(cdp,`(()=>{const vis=e=>e&&e.getClientRects().length>0;const sels=${JSON.stringify(cfg.composer)},comp=sels.flatMap(s=>[...document.querySelectorAll(s)]).find(e=>e.getAttribute('aria-hidden')!=='true'&&vis(e));if(!comp)return {clicked:false,reason:'NO_COMPOSER'};const scope=comp.closest('form')||comp.parentElement||document;const primary=[...scope.querySelectorAll('[data-testid="send-button"],button[type="submit"],button,[role="button"]')].filter(e=>vis(e)&&!e.disabled);const send=primary.find(e=>{const x=String(e.getAttribute('aria-label')||e.getAttribute('title')||e.innerText||e.textContent||'').trim();return e.matches('[data-testid="send-button"],button[type="submit"]')||/^(send|send message|submit|submit message)$/i.test(x)});if(send){send.click();return {clicked:true,label:String(send.getAttribute('aria-label')||send.getAttribute('title')||send.innerText||send.textContent||'')}}return {clicked:false,reason:'NO_SEND_IN_SCOPE',count:primary.length}})()`);
  if(click?.clicked)submitMethod='BUTTON_AFTER_SETTLE';
 }
 if(submitMethod==='ENTER_AFTER_SETTLE'){await cdp.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});await cdp.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13})}
 await sleep(1200);
 const commitEnd=Date.now()+15000;let commit=null;
 while(Date.now()<commitEnd){commit=await evaluate(cdp,`(()=>{const vis=e=>e&&e.getClientRects().length>0;const buttons=[...document.querySelectorAll('button,[role="button"]')].filter(vis),stop=buttons.some(e=>/stop/i.test(String(e.getAttribute('aria-label')||e.getAttribute('title')||e.innerText||e.textContent||''))&&!e.disabled);const sels=${JSON.stringify(cfg.responseRoots||[])},roots=sels.length?sels.flatMap(s=>[...document.querySelectorAll(s)]):[...document.querySelectorAll('pre,code,article,[data-message-author-role="assistant"],[class*="message" i],[class*="markdown" i],[class*="response" i],[class*="prose" i]')];return {stop,url:location.href,response_count:roots.length}})()`);if(commit.url!==beforeUrl||commit.stop||commit.response_count>beforeResponses){commit.committed=true;break}commit.committed=false;await sleep(500)}
 if(!commit?.committed)throw new Error(`E_SUBMIT_NOT_COMMITTED:${JSON.stringify(commit||{})}`);
 if(threadUrl&&!String(commit.url||'').startsWith(threadUrl))throw new Error(`E_DAILY_THREAD_DRIFT:${commit.url||''}`);
 if(dispatchReceiptFile)fs.writeFileSync(dispatchReceiptFile,JSON.stringify({schema:'die.h01.provider-dispatch.v1',status:'COMMITTED',provider,prompt_sha256:sha(prompt),conversation_url:commit.url,submit_method:submitMethod,commit_evidence:commit,committed_at:new Date().toISOString(),provider_reprompted:false},null,2)+'\n',{mode:0o640});
 const started=new Date().toISOString(),obslog=[];let best='',last='',stable=0;const deadline=Date.now()+timeoutMs;
 while(Date.now()<deadline){const snap=await responseSnapshot(cdp,cfg);if(threadUrl&&!String(snap.url||'').startsWith(threadUrl))throw new Error(`E_DAILY_THREAD_DRIFT:${snap.url||''}`);const fresh=(snap.svgs||[]).filter(x=>!baselineSvgHashes.has(sha(x)));const candidate=fresh.length?fresh[fresh.length-1]:'';obslog.push({at:new Date().toISOString(),svg_chars:candidate.length,candidates:fresh.length,baseline_candidates:baselineSvgHashes.size,stop_visible:snap.stop,url:snap.url});if(obslog.length>240)obslog.shift();if(candidate){best=candidate;if(best===last)stable++;else{last=best;stable=0}if(stable>=2&&!snap.stop)break}else stable=0;await sleep(1500)}if(!best)throw new Error('E_SVG_RESPONSE_TIMEOUT');fs.mkdirSync(path.dirname(responseFile),{recursive:true});fs.writeFileSync(responseFile,best+'\n',{mode:0o640});const result={status:'SUCCEEDED',provider,origin:cfg.origin,started_at:started,completed_at:new Date().toISOString(),submit_method:submitMethod,prompt_sha256:sha(prompt),response_sha256:sha(best),response_chars:best.length,completion_signal:'SVG_COMPLETE_STABLE_NO_STOP',observations:obslog};if(observationFile)fs.writeFileSync(observationFile,JSON.stringify(result,null,2)+'\n',{mode:0o640});console.log(JSON.stringify(result));
}finally{cdp.close()}
