#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const arg=(n,d='')=>{const i=process.argv.indexOf(n);return i>=0?String(process.argv[i+1]||''):d};
const num=(n,d)=>{const v=Number(arg(n,String(d)));return Number.isFinite(v)?v:d};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
class Cdp{constructor(url){this.url=url;this.ws=null;this.seq=0;this.pending=new Map()}async connect(){this.ws=new WebSocket(this.url);await new Promise((r,j)=>{const t=setTimeout(()=>j(new Error('E_CDP_WS_TIMEOUT')),1e4);this.ws.onopen=()=>{clearTimeout(t);r()};this.ws.onerror=()=>{clearTimeout(t);j(new Error('E_CDP_WS'))}});this.ws.onmessage=e=>{let m;try{m=JSON.parse(String(e.data))}catch{return}const p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message||'E_CDP_RPC')):p.resolve(m.result||{})}}send(method,params={}){const id=++this.seq;return new Promise((resolve,reject)=>{const t=setTimeout(()=>{this.pending.delete(id);reject(new Error(`E_CDP_RPC_TIMEOUT:${method}`))},2e4);this.pending.set(id,{resolve:v=>{clearTimeout(t);resolve(v)},reject:e=>{clearTimeout(t);reject(e)}});this.ws.send(JSON.stringify({id,method,params}))})}close(){try{this.ws?.close()}catch{}}}
async function ev(c,e){const r=await c.send('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw new Error('E_RUNTIME_EVALUATE');return r.result?.value}
async function target(port){const end=Date.now()+3e4;while(Date.now()<end){try{const rows=await(await fetch(`http://127.0.0.1:${port}/json/list`,{signal:AbortSignal.timeout(1500)})).json();const t=rows.find(x=>x.type==='page'&&String(x.url||'').startsWith('https://gemini.google.com'));if(t?.webSocketDebuggerUrl)return t}catch{}await sleep(250)}throw new Error('E_GEMINI_TARGET')}
const port=num('--cdp-port',0),promptFile=arg('--prompt-file'),outputFile=arg('--output-file'),downloadDir=arg('--download-dir'),obsFile=arg('--observation-file'),timeoutMs=num('--timeout-ms',600000);if(!port||!promptFile||!outputFile||!downloadDir)throw new Error('E_CONFIG');
fs.mkdirSync(downloadDir,{recursive:true});for(const n of fs.readdirSync(downloadDir))fs.rmSync(path.join(downloadDir,n),{recursive:true,force:true});const prompt=fs.readFileSync(promptFile,'utf8');const t=await target(port),c=new Cdp(t.webSocketDebuggerUrl);await c.connect();
try{await c.send('Runtime.enable');try{await c.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloadDir,eventsEnabled:true})}catch{await c.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:downloadDir})}
let probe=null;const readyEnd=Date.now()+45000;while(Date.now()<readyEnd){probe=await ev(c,`(()=>{const sels=['[contenteditable="true"][role="textbox"]','.ql-editor[contenteditable="true"]','[contenteditable="true"]','textarea'];const el=sels.flatMap(s=>[...document.querySelectorAll(s)]).find(e=>e.getClientRects().length>0&&e.getAttribute('aria-hidden')!=='true');return {composer:!!el}})()`);if(probe.composer)break;await sleep(500)}if(!probe?.composer)throw new Error('E_COMPOSER_NOT_READY');
const fill=await ev(c,`(()=>{const text=${JSON.stringify(prompt)},sels=['[contenteditable="true"][role="textbox"]','.ql-editor[contenteditable="true"]','[contenteditable="true"]','textarea'],el=sels.flatMap(s=>[...document.querySelectorAll(s)]).find(e=>e.getClientRects().length>0&&e.getAttribute('aria-hidden')!=='true');if(!el)return 0;el.focus();if('value'in el){const set=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el),'value')?.set;set?set.call(el,text):el.value=text;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}else{el.textContent='';document.execCommand('insertText',false,text);el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}))}return String(el.value??el.innerText??el.textContent??'').length})()`);if(fill<20)throw new Error('E_PROMPT_INJECT');await sleep(600);
const submit=await ev(c,`(()=>{const vis=e=>e&&e.getClientRects().length>0;const all=[...document.querySelectorAll('button,[role="button"]')];const send=all.find(e=>vis(e)&&!e.disabled&&/send message/i.test(String(e.getAttribute('aria-label')||e.innerText||e.textContent||'')));if(send){send.click();return 'BUTTON'}return 'KEYBOARD'})()`);if(submit==='KEYBOARD'){await c.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await c.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13})}
const started=new Date().toISOString(),deadline=Date.now()+timeoutMs,obs=[];let clicked=false,best='',last='',stableSvg=0;
while(Date.now()<deadline&&!clicked){const x=await ev(c,`(()=>{const vis=e=>e&&e.getClientRects().length>0;const all=[...document.querySelectorAll('button,a,[role="button"]')];const dl=all.find(e=>vis(e)&&/download\\s*svg/i.test(String(e.getAttribute('aria-label')||e.getAttribute('title')||e.innerText||e.textContent||'')));const stop=all.some(e=>vis(e)&&/stop( generating| response)?/i.test(String(e.getAttribute('aria-label')||e.getAttribute('title')||e.innerText||e.textContent||'')));const roots=[...document.querySelectorAll('pre,code')];const cand=[];for(const r of roots){const t=String(r.innerText||r.textContent||'');const a=t.indexOf('<svg'),b=t.lastIndexOf('</svg>');if(a>=0&&b>a){const z=t.slice(a,b+6).trim();if(z.length<=1048576)cand.push(z)}}cand.sort((a,b)=>a.length-b.length);if(dl){dl.click();return {clicked:true,stop,svg:cand[0]||'',svg_chars:(cand[0]||'').length,label:String(dl.getAttribute('aria-label')||dl.getAttribute('title')||dl.innerText||dl.textContent||'')}}return {clicked:false,stop,svg:cand[0]||'',svg_chars:(cand[0]||'').length}})()`);obs.push({at:new Date().toISOString(),clicked:x.clicked,stop:x.stop,svg_chars:x.svg_chars,label:x.label||null});if(x.clicked){clicked=true;break}if(x.svg){best=x.svg;if(best===last)stableSvg++;else{last=best;stableSvg=0}if(stableSvg>=2&&!x.stop)break}else stableSvg=0;await sleep(1500)}
let bytes=null,method=null,control=null;
if(clicked){let found=null,stable=-1;const fend=Date.now()+60000;while(Date.now()<fend){const files=fs.readdirSync(downloadDir).filter(n=>!n.endsWith('.crdownload')&&!n.endsWith('.tmp')).map(n=>path.join(downloadDir,n)).filter(p=>fs.statSync(p).isFile());const svg=files.find(p=>p.toLowerCase().endsWith('.svg'));if(svg){const z=fs.statSync(svg).size;if(z>0&&z===stable){found=svg;break}stable=z}await sleep(500)}if(!found)throw new Error('E_SVG_DOWNLOAD_MISSING');bytes=fs.readFileSync(found);method='UI_DOWNLOAD_SVG';control='Download SVG'}
else if(best){bytes=Buffer.from(best+'\n','utf8');method='DOM_TEXT_SVG_FALLBACK'}
else throw new Error('E_GEMINI_SVG_OUTPUT_TIMEOUT');
if(!bytes.toString('utf8').includes('<svg'))throw new Error('E_GEMINI_OUTPUT_NOT_SVG');fs.mkdirSync(path.dirname(outputFile),{recursive:true});fs.writeFileSync(outputFile,bytes,{mode:0o640});const r={status:'SUCCEEDED',provider:'gemini',started_at:started,completed_at:new Date().toISOString(),submit_method:submit,acquisition_method:method,provider_artifact_control:control,source_kind:method==='UI_DOWNLOAD_SVG'?'PROVIDER_FILE_DOWNLOAD':'PROVIDER_RESPONSE_TEXT',prompt_sha256:sha(Buffer.from(prompt)),output_sha256:sha(bytes),output_bytes:bytes.length,observations:obs.slice(-120)};if(obsFile)fs.writeFileSync(obsFile,JSON.stringify(r,null,2)+'\n',{mode:0o640});console.log(JSON.stringify(r));
}finally{c.close()}
