#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
const arg=(n,d='')=>{const i=process.argv.indexOf(n);return i>=0?String(process.argv[i+1]||''):d};
const num=(n,d)=>{const v=Number(arg(n,String(d)));return Number.isFinite(v)?v:d}; const sleep=ms=>new Promise(r=>setTimeout(r,ms)); const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
class Cdp{constructor(url){this.url=url;this.ws=null;this.seq=0;this.pending=new Map()}async connect(){this.ws=new WebSocket(this.url);await new Promise((r,j)=>{const t=setTimeout(()=>j(new Error('E_CDP_WS_TIMEOUT')),1e4);this.ws.onopen=()=>{clearTimeout(t);r()};this.ws.onerror=()=>{clearTimeout(t);j(new Error('E_CDP_WS'))}});this.ws.onmessage=e=>{let m;try{m=JSON.parse(String(e.data))}catch{return}const p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message||'E_CDP_RPC')):p.resolve(m.result||{})}}send(method,params={}){const id=++this.seq;return new Promise((resolve,reject)=>{const t=setTimeout(()=>{this.pending.delete(id);reject(new Error(`E_CDP_RPC_TIMEOUT:${method}`))},15e3);this.pending.set(id,{resolve:v=>{clearTimeout(t);resolve(v)},reject:e=>{clearTimeout(t);reject(e)}});this.ws.send(JSON.stringify({id,method,params}))})}close(){try{this.ws?.close()}catch{}}}
async function evaluate(cdp,expression){const r=await cdp.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw new Error(`E_RUNTIME_EVALUATE:${r.exceptionDetails.exception?.description||r.exceptionDetails.text||''}`);return r.result?.value}
async function target(port,origin){const end=Date.now()+3e4;while(Date.now()<end){try{const rows=await (await fetch(`http://127.0.0.1:${port}/json/list`,{signal:AbortSignal.timeout(1500)})).json();const t=rows.find(x=>x.type==='page'&&String(x.url||'').startsWith(origin));if(t?.webSocketDebuggerUrl)return t}catch{}await sleep(250)}throw new Error('E_PROVIDER_TARGET')}
const P={
 claude:{origin:'https://claude.ai',composer:['div[contenteditable="true"][role="textbox"]','[contenteditable="true"]','textarea'],responseRoots:['.font-claude-response']},
 chatgpt:{origin:'https://chatgpt.com',composer:['#prompt-textarea','textarea','[contenteditable="true"]'],responseRoots:['[data-message-author-role="assistant"]']},
 qwen:{origin:'https://chat.qwen.ai',composer:['textarea[placeholder*="Ask Qwen" i]','textarea','[contenteditable="true"][role="textbox"]','[contenteditable="true"]']},
 gemini:{origin:'https://gemini.google.com',composer:['[contenteditable="true"][role="textbox"]','.ql-editor[contenteditable="true"]','[contenteditable="true"]','textarea']},
 grok:{origin:'https://grok.com',composer:['[contenteditable="true"][role="textbox"]','[contenteditable="true"]','textarea']},
 manus:{origin:'https://manus.im',composer:['.tiptap.ProseMirror[contenteditable="true"]','textarea','[contenteditable="true"]']},
 copilot:{origin:'https://copilot.microsoft.com',composer:['textarea','[contenteditable="true"][role="textbox"]','[contenteditable="true"]']},
 duckai:{origin:'https://duck.ai',composer:['textarea[placeholder="Ask anything privately"]','textarea']}
};
const provider=arg('--provider'),cfg=P[provider],port=num('--cdp-port',0),promptFile=arg('--prompt-file'),responseFile=arg('--response-file'),observationFile=arg('--observation-file'),timeoutMs=num('--timeout-ms',360000);if(!cfg||!port||!promptFile||!responseFile)throw new Error('E_CONFIG');const prompt=fs.readFileSync(promptFile,'utf8');
const t=await target(port,cfg.origin),cdp=new Cdp(t.webSocketDebuggerUrl);await cdp.connect();
try{await cdp.send('Runtime.enable');
 let probe=null;const composerDeadline=Date.now()+45000;while(Date.now()<composerDeadline){probe=await evaluate(cdp,`(()=>{const sels=${JSON.stringify(cfg.composer)},el=sels.flatMap(s=>[...document.querySelectorAll(s)]).find(e=>e.getAttribute('aria-hidden')!=='true'&&e.getClientRects().length>0);const vis=e=>!!e&&(e.getClientRects().length>0);const login=[...document.querySelectorAll('button,a')].some(e=>vis(e)&&/^(log in|sign in)$/i.test((e.innerText||e.textContent||'').trim()));const body=(document.body?.innerText||'').toLowerCase(),challenge=/verify you are human|security check|captcha|unusual traffic/.test(body);return {composer:!!el,auth_required:!el&&(login||challenge),url:location.href,title:document.title}})()`);if(probe.auth_required)throw new Error('E_AUTH_REQUIRED');if(probe.composer)break;await sleep(500)}if(!probe?.composer)throw new Error('E_COMPOSER_NOT_READY');
 const fill=await evaluate(cdp,`(()=>{const text=${JSON.stringify(prompt)},sels=${JSON.stringify(cfg.composer)},el=sels.flatMap(s=>[...document.querySelectorAll(s)]).find(e=>e.getAttribute('aria-hidden')!=='true'&&e.getClientRects().length>0);if(!el)return {ok:false};el.focus();if(el instanceof HTMLTextAreaElement||el instanceof HTMLInputElement){const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;if(setter)setter.call(el,text);else el.value=text;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}else{el.textContent='';document.execCommand('insertText',false,text);if((el.innerText||el.textContent||'').length<20)el.textContent=text;el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}))}return {ok:true,chars:String(typeof el.value==='string'?el.value:(el.innerText||el.textContent||'')).length}})()`);if(!fill.ok||fill.chars<Math.min(20,prompt.length))throw new Error('E_PROMPT_INJECT');await sleep(600);
 let submitMethod='ENTER_AFTER_SETTLE';
 if(provider==='chatgpt'||provider==='copilot'){
  const click=await evaluate(cdp,`(()=>{const vis=e=>e&&e.getClientRects().length>0;const exact=[...document.querySelectorAll('[data-testid="send-button"],button,[role="button"]')].filter(e=>vis(e)&&!e.disabled);const c=exact.filter(e=>{const x=String(e.getAttribute('aria-label')||e.getAttribute('title')||e.innerText||e.textContent||'').trim();return /^(send|send message|submit|submit message)$/i.test(x)});if(c.length===1){c[0].click();return {clicked:true,label:String(c[0].getAttribute('aria-label')||c[0].getAttribute('title')||c[0].innerText||c[0].textContent||'')}}return {clicked:false,count:c.length}})()`);
  if(click?.clicked)submitMethod='BUTTON_AFTER_SETTLE';
 }
 if(submitMethod==='ENTER_AFTER_SETTLE'){await cdp.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});await cdp.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13})}await sleep(1200);
 const started=new Date().toISOString(),obslog=[];let best='',last='',stable=0;const deadline=Date.now()+timeoutMs;
 while(Date.now()<deadline){const obs=await evaluate(cdp,`(()=>{const sels=${JSON.stringify(cfg.responseRoots||[])};let roots=sels.length?sels.flatMap(s=>[...document.querySelectorAll(s)]):[...document.querySelectorAll('pre,code,article,[data-message-author-role="assistant"],[class*="message" i],[class*="markdown" i],[class*="response" i],[class*="prose" i]')];const seen=new Set(),c=[];for(const e of roots){const t=String(e.innerText||e.textContent||'').trim();if(!t||seen.has(t))continue;seen.add(t);const a=t.indexOf('<svg'),b=t.lastIndexOf('</svg>');if(a<0||b<=a)continue;const x=t.slice(a,b+6).trim(),oe=x.indexOf('>');if(oe<4)continue;const root=x.slice(0,oe+1).toLowerCase();if(!(root.includes('viewbox=')||root.includes('xmlns=')||root.includes('width=')))continue;if(x.length<=1048576)c.push(x)}c.sort((a,b)=>a.length-b.length);const buttons=[...document.querySelectorAll('button')],stop=buttons.some(b=>/stop( generating| response)?/i.test(String(b.getAttribute('aria-label')||b.getAttribute('title')||b.innerText||b.textContent||''))&&!b.disabled);return {svg:c[0]||'',svg_chars:(c[0]||'').length,candidates:c.length,stop_visible:stop,url:location.href,title:document.title}})()`);obslog.push({at:new Date().toISOString(),svg_chars:obs.svg_chars,candidates:obs.candidates,stop_visible:obs.stop_visible,url:obs.url});if(obslog.length>240)obslog.shift();if(obs.svg){best=obs.svg;if(best===last)stable++;else{last=best;stable=0}if(stable>=2&&!obs.stop_visible)break}else stable=0;await sleep(1500)}if(!best)throw new Error('E_SVG_RESPONSE_TIMEOUT');fs.mkdirSync(path.dirname(responseFile),{recursive:true});fs.writeFileSync(responseFile,best+'\n',{mode:0o640});const result={status:'SUCCEEDED',provider,origin:cfg.origin,started_at:started,completed_at:new Date().toISOString(),submit_method:submitMethod,prompt_sha256:sha(prompt),response_sha256:sha(best),response_chars:best.length,completion_signal:'SVG_COMPLETE_STABLE_NO_STOP',observations:obslog};if(observationFile)fs.writeFileSync(observationFile,JSON.stringify(result,null,2)+'\n',{mode:0o640});console.log(JSON.stringify(result));
}finally{cdp.close()}
