#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';
const arg=(n,d='')=>{const i=process.argv.indexOf(n);return i>=0?String(process.argv[i+1]||''):d};
const num=(n,d)=>{const v=Number(arg(n,String(d)));return Number.isFinite(v)?v:d};const sleep=ms=>new Promise(r=>setTimeout(r,ms));const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const CFG={
 chatgpt:{origin:'https://chatgpt.com',settle:12000,composers:['#prompt-textarea','[data-testid="prompt-textarea"]','[contenteditable="true"][data-testid="composer-text-input"]','[contenteditable="true"][role="textbox"]','[contenteditable="true"]','textarea'],send:['[data-testid="send-button"]','button[aria-label*="Send" i]','button[data-testid*="send" i]','form button[type="submit"]','button[aria-label*="Submit" i]'],roots:['[data-message-author-role="assistant"]']},
 gemini:{origin:'https://gemini.google.com',settle:3000,composers:['[contenteditable="true"][role="textbox"]','.ql-editor[contenteditable="true"]','[contenteditable="true"]','textarea'],send:['button[aria-label*="Send message" i]','button[aria-label*="Send" i]','button[type="submit"]'],roots:['pre','code']},
 copilot:{origin:'https://copilot.microsoft.com',settle:3000,composers:['textarea','[contenteditable="true"][role="textbox"]','[contenteditable="true"]'],send:['button[aria-label*="Submit" i]','button[aria-label*="Send" i]','button[type="submit"]','[role="button"][aria-label*="Submit" i]'],roots:['pre','code','article','[data-content="ai-message"]','[class*="response" i]']}
};
const provider=arg('--provider'),cfg=CFG[provider],port=num('--cdp-port',0),promptFile=arg('--prompt-file'),outputFile=arg('--output-file'),downloadDir=arg('--download-dir'),obsFile=arg('--observation-file'),timeoutMs=num('--timeout-ms',600000),pwEntry=arg('--playwright-entry','/opt/die/staging/income-os/company/muxia/node_modules/playwright/index.mjs');
if(!cfg||!port||!promptFile||!outputFile||!obsFile)throw new Error('E_CONFIG');if(!fs.existsSync(pwEntry))throw new Error('E_PLAYWRIGHT_MISSING');const prompt=fs.readFileSync(promptFile,'utf8').trim();fs.mkdirSync(path.dirname(outputFile),{recursive:true});if(downloadDir)fs.mkdirSync(downloadDir,{recursive:true});
const {chromium}=await import(pathToFileURL(pwEntry).href);const browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`,{timeout:15000});const context=browser.contexts()[0];if(!context)throw new Error('E_BROWSER_CONTEXT');
const page=context.pages().find(p=>String(p.url()).startsWith(cfg.origin));if(!page)throw new Error('E_PROVIDER_PAGE');await page.bringToFront();await page.waitForTimeout(cfg.settle);
const visible=async l=>await l.isVisible({timeout:300}).catch(()=>false);const textOf=async l=>String(await l.evaluate(el=>{const v=typeof el.value==='string'?el.value:'';return v||(el.innerText||el.textContent||'')}).catch(()=>'' )).trim();
async function challenge(){const body=String(await page.locator('body').innerText({timeout:2500}).catch(()=>'' )).toLowerCase();if(/verify you are human|security check|captcha|unusual traffic|checking your browser/.test(body))throw new Error('E_PROTECTION_CHALLENGE');if(/\/(login|signin|signup|auth)(?:\/|$)/i.test(new URL(page.url()).pathname))throw new Error('E_AUTH_REQUIRED');}
async function composer(){const end=Date.now()+45000;while(Date.now()<end){await challenge();for(const s of cfg.composers){const l=page.locator(s),n=Math.min(await l.count().catch(()=>0),20);for(let i=0;i<n;i++){const x=l.nth(i);if(!await visible(x))continue;const editable=typeof x.isEditable==='function'?await x.isEditable().catch(()=>false):true;if(editable)return{x,selector:s}}}await page.waitForTimeout(500)}throw new Error('E_COMPOSER_NOT_READY');}
function extractSvg(t){const a=t.indexOf('<svg'),b=t.lastIndexOf('</svg>');if(a<0||b<=a)return'';const x=t.slice(a,b+6).trim(),oe=x.indexOf('>');if(oe<4)return'';const root=x.slice(0,oe+1).toLowerCase();if(!(root.includes('viewbox=')||root.includes('xmlns=')||root.includes('width=')))return'';return x.length<=1048576?x:'';}
function geometrySignature(t){const tags=[...String(t||'').matchAll(/<(path|polygon|rect|circle|ellipse|line|polyline)\b[^>]*>/gi)].map(m=>m[0].replace(/\s+/g,' ').trim());return{count:tags.length,sha256:sha(tags.join('\n'))};}
async function candidates(){const vals=[];for(const s of cfg.roots){const l=page.locator(s),n=Math.min(await l.count().catch(()=>0),100);for(let i=0;i<n;i++){const t=String(await l.nth(i).innerText({timeout:500}).catch(()=>''));const x=extractSvg(t);if(x)vals.push(x)}}return[...new Map(vals.map(x=>[sha(x),x])).values()];}
async function stopVisible(){const l=page.locator('button,[role="button"]'),n=Math.min(await l.count().catch(()=>0),160);for(let i=0;i<n;i++){const x=l.nth(i);if(!await visible(x))continue;const z=String(await x.getAttribute('aria-label').catch(()=>null)||await x.getAttribute('title').catch(()=>null)||await x.innerText({timeout:200}).catch(()=>''));if(/stop( generating| response)?/i.test(z)&&await x.isEnabled().catch(()=>true))return true}return false;}
async function svgDownloadControls(){const l=page.locator('button,a,[role="button"]'),out=[];const n=Math.min(await l.count().catch(()=>0),220);for(let i=0;i<n;i++){const x=l.nth(i);if(!await visible(x))continue;const label=String(await x.getAttribute('aria-label').catch(()=>null)||await x.getAttribute('title').catch(()=>null)||await x.innerText({timeout:200}).catch(()=>''));if(/download\s*svg/i.test(label))out.push(x)}return out;}
async function bodyFailure(){const body=String(await page.locator('body').innerText({timeout:2500}).catch(()=>'' )).toLowerCase();if(/rate limit|too many requests|reached your limit/.test(body))throw new Error('E_PROVIDER_RATE_LIMITED');if(/generation failed|failed to generate|couldn.t generate|could not generate|something went wrong/.test(body))throw new Error('E_PROVIDER_GENERATION_FAILED');await challenge();}
async function fill(c,p){let method='locator-fill';try{await c.fill(p,{timeout:5000})}catch{}let now=await textOf(c);if(now.length<Math.min(20,p.length)){await c.click({timeout:1500});await page.keyboard.press('Control+A').catch(()=>{});await page.keyboard.type(p,{delay:2});method='keyboard-type';now=await textOf(c)}if(now.length<Math.min(20,p.length))throw new Error('E_PROMPT_INJECT');return method;}
async function clickSend(){for(const s of cfg.send){const l=page.locator(s),n=Math.min(await l.count().catch(()=>0),20);for(let i=0;i<n;i++){const x=l.nth(i);if(await visible(x)&&await x.isEnabled().catch(()=>false)){await x.evaluate(el=>el.click());return s}}}return'';}
async function commitEvidence(c,beforeUrl,beforeResponses,expectedPrompt=prompt){const end=Date.now()+18000;while(Date.now()<end){const txt=await textOf(c).catch(()=>''),stop=await stopVisible(),responses=(await candidates()).length,url=page.url();if(stop||txt.length<Math.min(20,expectedPrompt.length)||url!==beforeUrl||responses>beforeResponses)return{committed:true,url,composer_chars:txt.length,stop,response_count:responses};await page.waitForTimeout(500)}return{committed:false,url:page.url(),composer_chars:(await textOf(c).catch(()=>'' )).length,stop:await stopVisible(),response_count:(await candidates()).length};}
const baseCandidates=new Set((await candidates()).map(sha)),baseDownloads=provider==='gemini'?(await svgDownloadControls()).length:0,beforeUrl=page.url(),startedMs=Date.now(),started=new Date().toISOString();const {x:comp,selector:composerSelector}=await composer();const writeMethod=await fill(comp,prompt);let submitMethod='';
if(provider==='chatgpt'){await comp.press('Enter');submitMethod='composer-enter';let ce=await commitEvidence(comp,beforeUrl,baseCandidates.size);if(!ce.committed){const s=await clickSend();if(!s)throw new Error('E_SUBMIT_NOT_COMMITTED');submitMethod=s;ce=await commitEvidence(comp,beforeUrl,baseCandidates.size);if(!ce.committed)throw new Error('E_SUBMIT_NOT_COMMITTED')}}
else if(provider==='gemini'){await comp.press('Enter');submitMethod='composer-enter';let ce=await commitEvidence(comp,beforeUrl,baseCandidates.size);if(!ce.committed){const s=await clickSend();if(!s)throw new Error('E_SUBMIT_NOT_COMMITTED');submitMethod=s;ce=await commitEvidence(comp,beforeUrl,baseCandidates.size);if(!ce.committed)throw new Error('E_SUBMIT_NOT_COMMITTED')}}
else{await comp.press('Enter');submitMethod='composer-enter';let ce=await commitEvidence(comp,beforeUrl,baseCandidates.size);if(!ce.committed){const s=await clickSend();if(!s)throw new Error('E_SUBMIT_NOT_COMMITTED');submitMethod=s;ce=await commitEvidence(comp,beforeUrl,baseCandidates.size);if(!ce.committed)throw new Error('E_SUBMIT_NOT_COMMITTED')}}
let commit=await commitEvidence(comp,beforeUrl,baseCandidates.size);if(!commit.committed)throw new Error(`E_SUBMIT_NOT_COMMITTED:${JSON.stringify(commit)}`);
const observations=[],deadline=Date.now()+timeoutMs;let best='',last='',stable=0,rootlessStable=0,lastRootless='',emptyTerminalStable=0;
while(Date.now()<deadline){await bodyFailure();const stop=await stopVisible();if(provider==='gemini'){const controls=await svgDownloadControls();if(controls.length>baseDownloads){const control=controls[controls.length-1];try{const dlPromise=page.waitForEvent('download',{timeout:20000});await control.click({timeout:3000});const dl=await dlPromise;const rs=await dl.createReadStream();const chunks=[];for await(const z of rs)chunks.push(Buffer.from(z));const bytes=Buffer.concat(chunks);if(!bytes.length)throw new Error('E_EMPTY_DOWNLOAD');if(!bytes.toString('utf8').includes('<svg'))throw new Error('E_DOWNLOADED_NOT_SVG');fs.writeFileSync(outputFile,bytes,{mode:0o640});const result={status:'SUCCEEDED',provider,transport:'PLAYWRIGHT_CDP_ATTACH',started_at:started,completed_at:new Date().toISOString(),composer_selector:composerSelector,write_method:writeMethod,submit_method:submitMethod,dispatch_commit_evidence:commit,acquisition_method:'UI_DOWNLOAD_SVG',source_kind:'PROVIDER_FILE_DOWNLOAD',output_sha256:sha(bytes),output_bytes:bytes.length,observations};fs.writeFileSync(obsFile,JSON.stringify(result,null,2)+'\n',{mode:0o640});console.log(JSON.stringify(result));process.exit(0)}catch(e){observations.push({at:new Date().toISOString(),download_error:String(e).slice(0,300)})}}}
const cs=(await candidates()).filter(x=>!baseCandidates.has(sha(x)));if(cs.length){best=cs[0];if(best===last)stable++;else{last=best;stable=0}if(stable>=2&&!stop){const bytes=Buffer.from(best+'\n','utf8');fs.writeFileSync(outputFile,bytes,{mode:0o640});const result={status:'SUCCEEDED',provider,transport:'PLAYWRIGHT_CDP_ATTACH',started_at:started,completed_at:new Date().toISOString(),composer_selector:composerSelector,write_method:writeMethod,submit_method:submitMethod,dispatch_commit_evidence:commit,acquisition_method:'DOM_TEXT_SVG',source_kind:'PROVIDER_RESPONSE_TEXT',output_sha256:sha(bytes),output_bytes:bytes.length,response_chars:best.length,observations};fs.writeFileSync(obsFile,JSON.stringify(result,null,2)+'\n',{mode:0o640});console.log(JSON.stringify(result));process.exit(0)}}else stable=0;
if(provider==='gemini'&&!stop){const pre=page.locator('pre,code'),n=Math.min(await pre.count().catch(()=>0),100);let rootless='';for(let i=0;i<n;i++){const t=String(await pre.nth(i).innerText({timeout:400}).catch(()=>''));if(t.length>rootless.length&&!extractSvg(t))rootless=t}if(rootless.length>80){if(rootless===lastRootless)rootlessStable++;else{lastRootless=rootless;rootlessStable=0}if(rootlessStable>=3){const bytes=Buffer.from(rootless+'\n','utf8');fs.writeFileSync(outputFile,bytes,{mode:0o640});const result={status:'SUCCEEDED',provider,transport:'PLAYWRIGHT_CDP_ATTACH',started_at:started,completed_at:new Date().toISOString(),composer_selector:composerSelector,write_method:writeMethod,submit_method:submitMethod,dispatch_commit_evidence:commit,acquisition_method:'DOM_SVG_GEOMETRY_FRAGMENT',source_kind:'PROVIDER_RESPONSE_TEXT',output_sha256:sha(bytes),output_bytes:bytes.length,response_chars:rootless.length,provider_reprompted:false,observations};fs.writeFileSync(obsFile,JSON.stringify(result,null,2)+'\n',{mode:0o640});console.log(JSON.stringify(result));process.exit(0)}}else rootlessStable=0}
if(provider==='gemini'&&!stop&&Date.now()-startedMs>=60000&&cs.length===0){const body=String(await page.locator('body').innerText({timeout:1000}).catch(()=>''));const terminal=/Gemini said[\s\S]{0,160}(Flash|Pro|Thinking)/i.test(body.slice(-1200));if(terminal){emptyTerminalStable++;if(emptyTerminalStable>=3)throw new Error('E_GEMINI_EMPTY_TERMINAL')}else emptyTerminalStable=0}else emptyTerminalStable=0;
observations.push({at:new Date().toISOString(),url:page.url(),stop_visible:stop,svg_candidates:cs.length,best_chars:best.length});if(observations.length>240)observations.shift();await page.waitForTimeout(1500)}
throw new Error('E_SVG_RESPONSE_TIMEOUT');
