export const settleMs = 12000;
const COMPOSERS=['#prompt-textarea','[data-testid="prompt-textarea"]','[contenteditable="true"][data-testid="composer-text-input"]','[contenteditable="true"][role="textbox"]','[contenteditable="true"]','textarea'];
const AUTH='a:has-text("Log in"), button:has-text("Log in"), a:has-text("Sign up"), button:has-text("Sign up")';
function imageType(b){if(b.length>=8&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return{mime:'image/png',ext:'png'};if(b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255)return{mime:'image/jpeg',ext:'jpg'};if(b.length>=12&&b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP')return{mime:'image/webp',ext:'webp'};throw new Error('E_IMAGE_MAGIC');}
async function visible(l){return await l.isVisible({timeout:300}).catch(()=>false);}
async function composer(page){for(const s of COMPOSERS){const l=page.locator(s),n=Math.min(await l.count().catch(()=>0),20);for(let i=0;i<n;i++){const x=l.nth(i);if(!await visible(x))continue;if(typeof x.isEditable==='function'&&await x.isEditable().catch(()=>false))return x;}}return null;}
async function authRequired(page){const a=page.locator(AUTH),n=Math.min(await a.count().catch(()=>0),20);for(let i=0;i<n;i++)if(await visible(a.nth(i)))return true;try{return /\/(?:auth|login|signin|signup)(?:\/|$)/i.test(new URL(page.url()).pathname);}catch{return false;}}
async function challengeActive(page){const title=(await page.title().catch(()=>'' )).toLowerCase();if(/^just a moment/.test(title)||title.includes('attention required')||title.includes('security verification')||title.includes('checking your browser'))return true;for(const s of ['#challenge-running','#challenge-stage','[id*="cf-chl"]','[class*="cf-chl"]','iframe[src*="challenges.cloudflare.com"]'])if(await visible(page.locator(s).first()))return true;if(await composer(page))return false;const body=(await page.locator('body').innerText({timeout:2000}).catch(()=>'' )).toLowerCase();return ['verify you are human','checking your browser','security check','captcha','unusual activity'].some(x=>body.includes(x));}
async function images(page){return await page.locator('img').evaluateAll(xs=>xs.map(x=>({src:x.currentSrc||x.src||'',w:x.naturalWidth||0,h:x.naturalHeight||0,alt:(x.getAttribute('alt')||'').toLowerCase()})).filter(x=>x.src));}
async function sourceBytes(page,context,src){if(src.startsWith('data:image/')){const c=src.indexOf(',');if(c<0||!src.slice(0,c).includes(';base64'))throw new Error('E_DATA_URI');const bytes=Buffer.from(src.slice(c+1),'base64');return{bytes,...imageType(bytes),method:'provider_data_uri_dom'};}if(src.startsWith('blob:')){const b64=await page.evaluate(async u=>{const r=await fetch(u);const a=new Uint8Array(await r.arrayBuffer());let s='';for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(s);},src);const bytes=Buffer.from(b64,'base64');return{bytes,...imageType(bytes),method:'provider_blob_dom'};}if(/^https?:/.test(src)){const r=await context.request.get(src,{timeout:45000});if(!r.ok())throw new Error(`E_IMAGE_HTTP_${r.status()}`);const bytes=Buffer.from(await r.body());if(!bytes.length)throw new Error('E_EMPTY_IMAGE');let host='';try{host=new URL(src).hostname.toLowerCase()}catch{}return{bytes,...imageType(bytes),host,method:'provider_image_url_browser_context'};}throw new Error('E_IMAGE_SOURCE');}
export async function prepare({page}){if(await authRequired(page))throw new Error('E_AUTH_REQUIRED');if(await challengeActive(page))throw new Error('E_PROTECTION_CHALLENGE');for(const s of ['button[data-testid="close-button"]']){const l=page.locator(s),n=Math.min(await l.count().catch(()=>0),10);for(let i=0;i<n;i++)if(await visible(l.nth(i)))await l.nth(i).click({timeout:1000}).catch(()=>{});}const c=await composer(page);if(!c)throw new Error('E_CHATGPT_COMPOSER_UNAVAILABLE');return{composer:c,baseline:new Set((await images(page)).map(x=>x.src)),attempts:new Map()};}
export async function submit({prompt,state}){await state.composer.fill(prompt,{timeout:5000});await state.composer.press('Enter');return{composer_selector:'web-ai-adapter-compatible-chatgpt-composer',send_selector:'composer-enter'};}
export async function waitForOutput({page,context,state,timeoutMs}){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){for(const x of (await images(page)).reverse()){if(!x.src||state.baseline.has(x.src)||x.w<512||x.h<512)continue;const eligible=x.alt.includes('generated image')||x.src.includes('/backend-api/estuary/content')||x.src.includes('oaiusercontent.com');if(!eligible)continue;const n=(state.attempts.get(x.src)||0)+1;state.attempts.set(x.src,n);if(n>8)continue;try{const got=await sourceBytes(page,context,x.src);if(got.bytes.length<50000)continue;return{...got,width:x.w,height:x.h,dom_kind:'img',alt:x.alt};}catch{}}
if(await authRequired(page))throw new Error('E_AUTH_REQUIRED');if(await challengeActive(page))throw new Error('E_PROTECTION_CHALLENGE');const body=(await page.locator('body').innerText({timeout:2500}).catch(()=>'' )).toLowerCase();if(body.includes("couldn't generate")||body.includes('could not generate')||body.includes('generation failed'))throw new Error('E_PROVIDER_GENERATION_FAILED');if(body.includes('rate limit')||body.includes('too many requests')||body.includes('reached your limit'))throw new Error('E_PROVIDER_RATE_LIMITED');await page.waitForTimeout(750);}throw new Error('E_BOUNDED_COMPLETION_TIMEOUT');}
export async function cleanup(){}
