import importlib.util,json,sys,tempfile,unittest
from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[2]; E=R/'company/company-os/die-h01/engineering'; sys.path.insert(0,str(E)); S=importlib.util.spec_from_file_location('m',E/'marketplace_real_upload_preflight.py'); M=importlib.util.module_from_spec(S); S.loader.exec_module(M)
class T(unittest.TestCase):
 def test_preflight(self):
  with tempfile.TemporaryDirectory() as td:
   r=Path(td); w=r/'ws'; p=w/'postproduction'; p.mkdir(parents=True); svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100"/></svg>'; (p/'optimized-master.svg').write_text(svg); (p/'canonical-master.svg').write_text(svg); (p/'master.eps').write_text('%!PS-Adobe-3.0 EPSF-3.0\n%%BoundingBox: 0 0 4000 4000\n'); Image.new('RGB',(2000,2000),'white').save(p/'preview.jpg','JPEG'); (w/'metadata.json').write_text(json.dumps({'title':'Bag','description':'Vector bag','keywords':['bag'],'ai_generated':True,'ai_disclosure':'GENERATIVE_AI','semantic_asset_id':'SEM-H109A'})); (w/'rights-signal.json').write_text(json.dumps({'result':'REVIEW_REQUIRED'})); live=r/'live'; live.mkdir(); (live/'submission-ready-index.json').write_text(json.dumps({'entries':[],'eligible_count':0,'external_action':'NONE'})); x=M.run_preflight(w,r/'out',observed_at='2026-09-14T05:20:00Z',live_submission_ready_root=live); self.assertEqual(x['status'],'PASS'); self.assertEqual(x['marketplace_package_count'],6); self.assertEqual(x['isolated_submission_ready']['eligible_count'],0); self.assertEqual(x['founder_handoff']['real_upload_task'],'H01-109B'); self.assertTrue(x['source_immutable']); t=x['transport_idempotency']; self.assertTrue(t['exact_replay_same_receipt'] and t['duplicate_scope_conflict_blocked']); self.assertEqual(t['durable_receipt_count'],1); self.assertFalse(t['external_action_performed'] or t['credential_accessed']); self.assertTrue(all(set(v['actions'].values()) <= {None,'NONE'} for v in x['marketplaces'].values()))
if __name__=='__main__': unittest.main()
